version: '3.8'

services:
  # bot:
  #   container_name: bot
  #   build: .

  redis:
    container_name: redis-db
    build: ./db/redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    # networks:
    #   - webnet

volumes:
  # postgres:
  redis:
